name: CI Pipeline with Discord Alerts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Rodar script (exemplo)
        run: echo "Rodando testes..."

      - name: Enviar alerta para o Discord
        if: always()
        run: |
          STATUS="${{ job.status }}"
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"🚀 Workflow finalizado com status: **$STATUS** no repositório $GITHUB_REPOSITORY\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
